benj652/TAHours

- frontend/package-lock.json
- frontend/package.json
Created folders so that we may work on frontend.
> Created folder structure for frontend pages, components, and mocks

- frontend/src/App.tsx
- frontend/src/main.tsx
- frontend/src/pages/analyticsPage/AnalyticsPage.tsx
- frontend/src/pages/analyticsPage/index.ts
- frontend/src/pages/feedPage/FeedPage.tsx
- frontend/src/pages/feedPage/index.ts
- frontend/src/pages/index.ts
- frontend/src/pages/loginPage/LoginPage.tsx
- frontend/src/pages/loginPage/index.ts
- frontend/src/pages/mainPage/MainPage.tsx
- frontend/src/pages/mainPage/index.ts
- frontend/src/pages/profilePage/ProfilePage.tsx
- frontend/src/pages/profilePage/index.ts
> Added basic file for each page and implemented url router

- frontend/.env.example
- frontend/package-lock.json
- frontend/package.json
- frontend/vite.config.ts
> changed the port to 3000

- frontend/src/components/feed/Post.tsx
- frontend/src/components/feed/Posts.tsx
- frontend/src/components/feed/Replies.tsx
- frontend/src/components/feed/Reply.tsx
- frontend/src/components/feed/WritePost.tsx
- frontend/src/components/feed/WriteReply.tsx
- frontend/src/components/feed/index.tsx
- frontend/src/components/index.ts
- frontend/src/pages/feedPage/FeedPage.tsx
Not great looking, I have my first draft commented under that was low key better but I don't think it was a great way to set it up so I started again. I will retackle this once I know more CSS. Originally I used flex, second iteration was just basic DasiyUi, might try a grid later because Ben says those are good. Need to add WriteReply and WritePost, but right now my brain is pretty fried.
> Feed page started

- frontend/src/pages/profilePage/ProfilePage.tsx
I have mocked up a profile page, with a picture, user info, and a classes + tickets list . Currently the build uses props which will have to be replaced with hooks once the middleware is done.
> Skeleton Profile Page

- frontend/src/App.tsx
- frontend/src/components/navbar/NavBar.tsx
- frontend/src/components/navbar/NavBarButton.tsx
- frontend/src/components/navbar/index.ts
- frontend/src/index.css
Title. Still needs to make the buttons disabled for the page you are on.
> Made Epic Navbar

- frontend/src/components/feed/Post.tsx
- frontend/src/components/feed/Replies.tsx
- frontend/src/components/feed/Reply.tsx
- frontend/src/pages/feedPage/FeedPage.tsx
Feed page looks better, works on half and full screens. Probably doesn't work on mobile but that's frankly beyond my skill level. Write post and write reply will be coming shortly.
> Feed page looks pretty good now. Write post and write reply on the way.

- frontend/src/components/feed/WritePost.tsx
- frontend/src/components/feed/WriteReply.tsx
- frontend/src/pages/feedPage/FeedPage.tsx
> Created WriteReply and WritePost components for feed page.

- frontend/src/components/index.ts
- frontend/src/components/mainPage/ResolvePopup.tsx
- frontend/src/components/mainPage/index.ts
- frontend/src/pages/mainPage/MainPage.tsx
> added a starteer for the popup to resolve tickers

- frontend/src/components/mainPage/queueCard/queuePopups/AddTicketPopup.tsx
- frontend/src/pages/analyticsPage/AnalyticsPage.tsx
> removed resolve popup as it is gone

- backend/app/app.go
- backend/controllers/ticket_controller.go
- backend/models/ticket_model.go
- count_line.sh
- frontend/src/components/mainPage/queueCard/queuePopups/AddTicketPopup.tsx
- frontend/src/components/mainPage/queueCard/queuePopups/ResolveTicketPopup.tsx
- frontend/src/hooks/tickets/useCreateTicket.ts
- frontend/src/hooks/tickets/useResolveTicket.ts
- frontend/src/types/tickets.ts
Finished off the connections on the main page. I ignored the UI for now so that will need to be fixed. You can now create + resolve tickets, with images and what not, join sessions, leave sessions, create queues, all the fun stuff.
> Final Main Page Connections

- frontend/src/components/feed/WritePost.tsx
- frontend/src/components/feed/WriteReply.tsx
- frontend/src/hooks/posts/useCreatePost.ts
- frontend/src/hooks/posts/useGetAllPosts.ts
The posts are not cached so we do not have to fetch them every time we click on the page.
> Made the thread store work

- frontend/src/components/analytics/AnalyticPieChart.tsx
- frontend/src/components/analytics/ClassList.tsx
- frontend/src/components/analytics/SearchFilter.tsx
- frontend/src/components/analytics/TextAnalytics.tsx
- frontend/src/components/analytics/TicketQueue.tsx
- frontend/src/components/analytics/index.ts
- frontend/src/components/index.ts
- frontend/src/pages/analyticsPage/AnalyticsPage.tsx
finished UI mockup for the analytics view and cleaned up the look
> Final UI for Analytics

- frontend/src/components/analytics/SearchableDropdown.tsx
- frontend/src/pages/analyticsPage/AnalyticsPage.tsx
- frontend/src/pages/feedPage/FeedPage.tsx
> Fixed a max depth exceeded bug on the thread page

- frontend/src/components/mainPage/addTaQueue/AddTaQueueButton.tsx
- frontend/src/components/mainPage/addTaQueue/AddTaQueuePopup.tsx
- frontend/src/components/mainPage/queueCard/AddTicketButton.tsx
- frontend/src/components/mainPage/queueCard/Ticket.tsx
- frontend/src/components/mainPage/queueCard/Tickets.tsx
- frontend/src/components/mainPage/queueCard/queuePopups/AddTicketPopup.tsx
- frontend/src/components/mainPage/queueCard/queuePopups/QueuePopup.tsx
- frontend/src/components/mainPage/queueCard/queuePopups/ResolveTicketPopup.tsx
- frontend/src/components/mainPage/taCard/ActiveTa.tsx
- frontend/src/components/mainPage/taCard/ActiveTas.tsx
- frontend/src/components/mainPage/taCard/JoinSessionButton.tsx
- frontend/src/components/mainPage/taCard/LeaveSessionButton.tsx
Main Page CSS was made to fit with rest of site style wise.
> Cleaned Up CSS

- frontend/src/components/mainPage/addTaQueue/AddTaQueuePopup.tsx
Fixed a misscopied file that was messed up when I had to reclone the repo
> Copied wrong file over

- frontend/src/components/mainPage/addTaQueue/AddTaQueuePopup.tsx
- frontend/src/components/mainPage/queueCard/queuePopups/AddTicketPopup.tsx
fixed improperly copied over files
> Fixing one more failed copy

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/navbar/NavBar.tsx
- frontend/src/hooks/user/updateRoleHooks/useUpdateRoleProfessor.ts
- frontend/src/hooks/user/updateRoleHooks/useUpdateRoleStudent.ts
- frontend/src/hooks/user/updateRoleHooks/useUpdateRoleTA.ts
- frontend/src/hooks/user/useGetAllUsers.ts
- frontend/src/hooks/user/useGetUser.ts
- frontend/src/hooks/user/useLogin.ts
- frontend/src/hooks/user/useLogout.ts
This pull request includes several changes to the frontend codebase, focusing on adding a new dependency, refactoring imports, updating role hooks, and enhancing documentation. The most important changes are summarized below:
* Added `lucide-react` as a new dependency in `frontend/package-lock.json` and `frontend/package.json`. [[1]](diffhunk://#diff-4a2d9aa3e849b134993936ca81b83fb139edd2b0218077ab0f403b8c4803c62aR17) [[2]](diffhunk://#diff-4a2d9aa3e849b134993936ca81b83fb139edd2b0218077ab0f403b8c4803c62aR3411-R3419) [[3]](diffhunk://#diff-da6498268e99511d9ba0df3c13e439d10556a812881c9d03955b2ef7c6c1c655R19)
* Refactored imports and usage of `rolesConfig` and `routes` to `RolesConfig` and `Routes` in `frontend/src/components/navbar/NavBar.tsx`. …
> Qucik fixes from merge issue

- frontend/src/components/analytics/AnalyticPieChart.tsx
- frontend/src/components/analytics/classManagement/AddClassForm.tsx
- frontend/src/components/analytics/classManagement/ClassList.tsx
- frontend/src/components/analytics/middleCol/MiddleCol.tsx
- frontend/src/components/analytics/middleCol/TicketQueue.tsx
- frontend/src/components/navbar/NavBar.tsx
- frontend/src/pages/analyticsPage/AnalyticsPage.tsx
I changed some UI on the analytics page and fixed overlap
> Analytics UI changes

- frontend/src/components/navbar/NavBar.tsx
The gray was wrong under the colby logo
> Most Important Change

- frontend/package-lock.json
- frontend/package.json
- frontend/src/hooks/csClass/useCreateCSClass.ts
- frontend/src/hooks/csClass/useGetActiveClasses.ts
- frontend/src/hooks/csClass/useGetCSClass.ts
- frontend/src/hooks/csClass/userCreateTaQueue.ts
- frontend/src/main.tsx
> Added toasts for Cs Class

- frontend/src/components/mainPage/queueCard/AddTicketButton.tsx
- frontend/src/components/mainPage/queueCard/Ticket.tsx
- frontend/src/components/mainPage/queueCard/queuePopups/AddTicketPopup.tsx
- frontend/src/components/mainPage/queueCard/queuePopups/QueuePopup.tsx
- frontend/src/components/mainPage/queueCard/queuePopups/ResolveTicketPopup.tsx
The issues was that each rendered queue button relied on the same modal, which caused conflicts
I made each modal use their queue id as their identifier through concatination:
```js
<dialog id={`${Modals.QueuePopup}${taQueueId}`} className="modal">
```
When the current ticket changed, the component did not re-render, causing the displayed user to just be the one from the last ticket clicked on,
Just changed the `useEffect` that was being used to mount the call to get the user by adding the current ticket to its dependency array
> Fixed User display bug and fixed queues not working bug

- frontend/src/pages/profilePage/ProfilePage.tsx
Changed Profile UI to match current design plan and removed unnecessary bloat
> Updated Profile UI

- frontend/src/components/profile/StudentTickets.tsx
- frontend/src/components/profile/TicketPopup.tsx
- frontend/src/hooks/tickets/index.ts
- frontend/src/hooks/tickets/useUserTickets.ts
- frontend/src/pages/profilePage/ProfilePage.tsx
> Profiletickets

- frontend/src/components/profile/TicketPopup.tsx
I fixed an error that popped when a ticket was unresolved and therefore had null ta fields
> fixed ticket popup error

- frontend/src/components/mainPage/queueCard/Tickets.tsx
- frontend/src/hooks/general/useListenMainPage.ts
> trying to fix the new tickets not rendering

- frontend/src/App.tsx
- frontend/src/hooks/general/useListenMainPage.ts
Trying to fix that ui bug again on the main page with the websockets and creating tickets. I think I may have got it this time
> Fix attempt two

- frontend/src/components/analytics/classManagement/ClassList.tsx
- frontend/src/components/analytics/middleCol/MiddleCol.tsx
- frontend/src/components/analytics/middleCol/TextAnalytics.tsx
- frontend/src/components/analytics/middleCol/TicketDisplay.tsx
- frontend/src/components/analytics/middleCol/TicketQueue.tsx
- frontend/src/hooks/taQueue/useGetClassQueues.ts
- frontend/src/pages/analyticsPage/AnalyticsPage.tsx
- frontend/src/types/taQueue.ts
Title. Made it so it shows sessions correctly. Should be good to merge but someone should also test.
> Analytics page bugs fixed
